### ISSUE TITLE
[PE-D] Name does not allow for unique name types

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-W15-1/tp#206]
![image.png](https://raw.githubusercontent.com/imrajsinghsandhu/ped/main/files/b285c2ad-113f-407e-a2ec-48a4173d5411.png)

Some job applicants may have different names, and their names may not be able to be input into the system.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: imrajsinghsandhu/ped#4

**Comment by seanleong339** [comment]
Suggestion, not bug. Also mentioned in error message that name should only contain alphanumeric characters.
